# D0CSTRINGS
# PEP-8

# PYTHON DOCSTRINGS ARE THE STRINGS LITERALS THAT APPEAR RIGHT AFTER THE DEFINATION OF A FUCNTION, METHOD, CLASS, OR MODULE 

def square (n):
    '''takes in a number n, returns the square of n'''
    print(n**2)
square()
print(square.__doc__)

# docstring should be written just below the function

# comments and docstrings are different

# python enhancement proposel pep-8
import this
# this prints the zen of python

