/// PAINTERS PARTITION PROBLEM
/*
K ---> PAINTERS
1 UNIT BOARD ---> 1 UNIT TIME
PAINTER ---> CAN ONLY PAINT CONTINUOUS SECTION

WHAT IS THE MINIMUM TIME TO PAINT AN ARRAY ?
*/

/*
/ GIVEN AN ARRAY-LIST OF LENGTH 'N' , WHERE THE ARRAY-LIST REPRESENTS THE BOARDS AND EACH ELEMENT OF THE GIVEN ARRAY-LIST REPRESENTS THE LENGTH OF EACH BOARD. SOME 'K' NUMBERS OF POINTERS ARE AVAILABLE TO PAINT THESE BOARDS. CONSIDER THTA EACH UNIT OF A BOARD TAKES 1 UNIT OF TIME TO POINT.
* U R SUPPOSED TO RETURN THE AREA OF THE MINIMUM TIME TO GET THIS JOB DONE OF PAINTING ALL THE 'N' BOARDS UNDER A CONSTRAINT THAT ANY POINTER WILL ONLY PAINT THE CONTINUOUS SECTIONS OF BOARDS.

*/