# ESCAPE SEQUENCE CHARACTER 
''' i.e to inset characters that cannot be directly used in a string , we use an escape sequence character 
- it is started by a "\" backslash and followed by the character u want to insert
'''
print("today i am learning python,\na coding language ")
#/   \n for a new line 

#for comments use # or '''-''' , so that python wont execute it - 
# it can be used to inform about the code ahead or for  heading , it can be used anywhere.

'''this is to just to inform about he code ahead'''

print("hey \"i\" am \"AAJ\" ")
print()

# there can be multiple values in print 

print( "AAJ" , 87 , (78*48), True, sep=" -_- " , end="007\n" )
print("MRK")

# sep = separator , the default separator between two values in a function is space 
# end = for a new line after one function is executed , 
# these parameters are optional , they may or may not be used , and still the code will be same 

